### ISSUE TITLE
Reading role configuration via .yaml can lead to NullPointerException

### ISSUE THREAD

**Issue by mrAtFW** [Frachtwerk/essencium-backend#407]
**Describe the bug**
When creating a role via config file, a non existing role lead to an exception when updating existing roles. 

**To Reproduce**
1. add non existing role to role
```
essencium:
  init:
    roles:
      - name: <EXISTING_ROLE>
        rights:
          - <NON_EXISTING_RIGHT>
```
2. Start backend
3. NullPointer

**Expected behavior**
misconfiguration should only lead to warnings not system failure
